var style = document.createElement('style');
    // NEW CSS DOCUMENT
    var css =  '#newPersonalizationPanel .col-xs-4,#newPersonalizationPanel .col-xs-8{width:auto}#newPersonalizationPanel .personalize-options>div{padding:10px 0;justify-content:center;align-items:flex-start}#newPersonalizationPanel .personalize-options input{width:25px}#newPersonalizationPanel .personalize-options{display:flex;flex-direction:column;flex-wrap:nowrap;justify-content:space-evenly;align-items:stretch;align-content:center;width:100%}#newPersonalizationPanel .row{display:flex;flex-direction:column;align-items:flex-start;margin:0}#newPersonalizationPanel{border:1px solid #ccc;border-radius:15px;margin:30px 10px 10px;width:95%;padding:15px}#newPersonalizationPanel .personalize-title{padding:10px 0 0;margin-bottom:0;text-align:center;width:100%}#newPersonalizationPanel .row.personalize-groups.borders{border-top:1px solid #00000052;width:100%;margin-top:20px;padding:0;display:flex;align-items:stretch}.row.personalize-groups.borders #CENTER{padding:10px 10px 5px;width:100%}.personalize-text-field{margin-bottom:0}.personalize-field-title{margin-top:20px}@media screen and (min-width:480px){.personalize-options label{margin:0;padding:0;height:auto}.personalize-options>div{display:flex;text-align:center;padding:10px}#newPersonalizationPanel .personalize-options input{margin-top:6px}}@media screen and (min-width:820px){#newPersonalizationPanel{margin:20px 20px 20px 60px;width:90%;border-radius:50px}#newPersonalizationPanel .personalize-options label{line-height:20px;display:flex;align-items:center;flex-direction:column;padding:0 6px;margin:0}#newPersonalizationPanel .personalize-options{flex-direction:row;margin-bottom:10px}#newPersonalizationPanel .personalize-title{padding:5px 0 0}#newPersonalizationPanel .row.personalize-groups.borders{margin:30px 5px}}'
    style.type = 'text/css';
    if (style.styleSheet) {
        style.styleSheet.cssText = '';
    } else {
        style.appendChild(document.createTextNode(css));
    }
    document.getElementsByTagName('head')[0].appendChild(style);